version: '3'

services:  

  mongodb:
    build: ./mongodb
    ports:
    - '27017:27017'

  postgresql:
    build: ./postgresql
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=test
    ports:
    - '5432:5432'

