version: '3'

services:  

  mongodb:
    build: ./mongodb
    ports:
    - '27017:27017'

  postgresql:
    build: ./postgresql
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=test
    ports:
    - '5432:5432'

#  elasticsearch:
#    build: elasticsearch:6.6.1
#    ports:
#      - 9200:9200
#      - 9300:9300